  {{config(materialized='table')}}

  select 
  EMP_ID AS EMPLOYEE_ID,
  EMP_NAME AS EMPLOYEE_NAME,
  CASE WHEN DEPARTMENT='HR' THEN 'HUMAN RESOURCE' ELSE DEPARTMENT END AS EMPLOYEE_DEPARTMENT,
  SALARY AS EMPLOYEE_SALARY,
  HIRE_DATE AS EMPLOYEE_HIRE_DATE
     from 
  {{sorce(ANALYTICS,'EMPLOYEES')}}