SELECT
    DEPARTMENT,
    COUNT(*) AS TOTAL_EMPLOYEES,
    AVG(SALARY) AS AVERAGE_SALARY,
    MIN(HIRE_DATE) AS FIRST_HIRE_DATE,
    MAX(HIRE_DATE) AS LATEST_HIRE_DATE
FROM {{ ref('sample_model_script') }}
GROUP BY DEPARTMENT
--ORDER BY TOTAL_EMPLOYEES DESC;